language: php

before_script:
  - wget https://getcomposer.org/composer.phar
  - chmod +x composer.phar
  - ./composer.phar update
  - ./composer.phar install


script:
  - mkdir coverage-report
  - ./bin/phpunit --coverage-clover coverage.xml --coverage-html coverage-report --log-tap tap.tap
